import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className='dark'>
			<body
				className={`${inter.className} bg-gradient-to-tr from-white via-gray-100 to-gray-300 dark:from-black dark:via-gray-900 dark:to-teal-900`}
			>
				{children}
			</body>
		</html>
	)
}
