import GlobalProviders from '@/contexts/global-providers'
import { Theme } from '@/libs/types'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const theme = (cookies().get('theme')?.value || 'dark') as Theme

	return (
		<html lang='en' className={theme} style={{ colorScheme: theme }}>
			<body className={inter.className}>
				<GlobalProviders theme={theme}>{children}</GlobalProviders>
			</body>
		</html>
	)
}
